name: poltter

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  poltter:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /poltter') ||
      startsWith(github.event.comment.body, '/poltter')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Run poltter
        uses: poltter-group/poltter/github@2c14fc5586fe0b88e5c04732d2e846769cc35671 # latest
        env:
          POLTTER_API_KEY: ${{ secrets.POLTTER_API_KEY }}
          POLTTER_PERMISSION: '{"bash": "deny"}'
        with:
          model: poltter/claude-opus-4-5
